// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RateUsecase is an autogenerated mock type for the RateUsecase type
type RateUsecase struct {
	mock.Mock
}

// ProcessBackgroundRate provides a mock function with given fields: ctx
func (_m *RateUsecase) ProcessBackgroundRate(ctx context.Context) {
	_m.Called(ctx)
}

// ProcessBackgroundRef provides a mock function with given fields: ctx
func (_m *RateUsecase) ProcessBackgroundRef(ctx context.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewRateUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewRateUsecase creates a new instance of RateUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRateUsecase(t mockConstructorTestingTNewRateUsecase) *RateUsecase {
	mock := &RateUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
