package domain

// Generated by https://quicktype.io

type AccountResponse struct {
	List   []Details `json:"list"`
	Status string    `json:"status"`
}

type Details struct {
	Acc     string `json:"acc"`
	CcyID   string `json:"ccyId"`
	Balance string `json:"balance"`
}
