package domain

// Generated by https://quicktype.io

type VerifyPassword struct {
	BaseResponse
	UserInfo UserInfo `json:"userInfo,omitempty"`
}

type UserInfo struct {
	ID    string `json:"id,omitempty"`
	Label string `json:"label,omitempty"`
	Name  string `json:"name,omitempty"`
	Ph    string `json:"ph,omitempty"`
	Email string `json:"email,omitempty"`
	Ktp   string `json:"ktp,omitempty"`
	Dob   string `json:"dob,omitempty"`
	Cif   string `json:"cif,omitempty"`
	Reset string `json:"reset,omitempty"`
}

type BaseResponse struct {
	Status string `json:"status"`
	Ph     string `json:"ph,omitempty"`
	UUID   string `json:"uuid,omitempty"`
	Mail   string `json:"mail,omitempty"`
}
