steps:
#build steps
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/webserver:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/webserver:latest', '.' ]

images:
- 'gcr.io/$PROJECT_ID/webserver'