authentication:
  signMethod: "RS256"
  param: "param"
  secret: "mysecret"
  privPath: "../../configs/jwt.key"
  pubPath: "../../configs/jwt.key.pub"
  authExp: 24h
  refExp: 168h
  fxIssuer: "sinarmas_fx"
  refPref: "REFRESH-%v"
  authPref: "AUTH-%v"
  isPersistent: true

wamp:
  realm: "sinarmas.realm"
  authenticatedRealm: "sinarmas.auth.realm"
  path: "/ws"
  authPath: "/authWs"
  protocol: "tcp"
  reftopic: "REF"
  ratetopic: "RATE"
  enablemetakill: false

server:
  address: "127.0.0.1"
  port: 8080
  level: debug

client:
  onboardingTimeoutMillis: 1000
  legacyBaseUrl: http://localhost:3001/

redis:
  address: localhost:6381
  timeout: 30
  offRatesChannel: OFF_RATE
  onRatesChannel: ON_RATE
  miscChannel: MISC
  refsMap:
    refs:pair: pair
    refs:currency: currency
    refs:configuration: configuration
    refs:mobilenewsitem: mobilenewsitem

historic:
  mapKey:
    604800000: tsHourlyRate:%s:%s
    7884000000: tsDailyRate:%s:%s
    157700000000: tsMonthlyRate:%s:%s

log:
  level: DEBUG
  format: text